[package]
name = "master-rust-types-generic_bin"
version = "0.1.0"
edition = "2021"
autobins = true


[[bin]]
doc = true
name = "master-rust-types-generic-main"
path = "src/master-rust-types-generic-main.rs"
