[package]
edition = "2021"
name = "knoldus_bin"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
knoldus_lib = { path = "../knoldus_lib",  optional = false , default-features = true}



