[package]
name = "other-types-string_bin"
version = "0.1.0"
edition = "2021"
autobins = true

[dependencies]
num="0.4.0"

[[bin]]
doc = true
name = "other-types-string-main"
path = "src/other-types-string-main.rs"
