[package]
name = "rust-doc-smartpointer-ref-cell_bin"
version = "0.1.0"
edition = "2021"



[[bin]]
doc = true
name = "rust-doc-smartpointer-ref-cell-main"
path = "src/rust-doc-smartpointer-ref-cell-main.rs"
