[package]
name = "packtpub-thread-rayon_bin"
version = "0.1.0"
edition = "2021"
autobins = true

[dependencies]
rayon = "1.0.0"

[[bin]]
doc = true
name = "packtpub-thread-rayon-main"
path = "src/packtpub-thread-rayon-main.rs"
