[package]
name = "rust-egg-struct_bin"
version = "0.1.0"
edition = "2021"
autobins = true

[dependencies]
proptest="1.0.0"

[[bin]]
doc = true
name = "rust-egg-struct-main"
path = "src/rust-egg-struct-main.rs"
