[package]
name = "rust-in-action-types-generic_bin"
version = "0.1.0"
edition = "2021"
autobins = true

[dependencies]
proptest="1.0.0"

[[bin]]
doc = true
name = "rust-in-action-types-generic-main"
path = "src/rust-in-action-types-generic-main.rs"
