[package]
name = "master-rust-lifetime-generic_bin"
version = "0.1.0"
edition = "2021"
autobins = true

[[bin]]
doc = true
name = "master-rust-lifetime-generic-main"
path = "src/master-rust-lifetime-generic-main.rs"
