[package]
name = "packtpub-lifetime-static_bin"
version = "0.1.0"
edition = "2021"
autobins = true


[[bin]]
doc = true
name = "packtpub-lifetime-static-main"
path = "src/packtpub-lifetime-static-main.rs"
