[package]
name = "master-rust-lazy_bin"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"

[[bin]]
doc = true
name = "master-rust-lazy-main"
path = "src/master-rust-lazy-main.rs"
