[package]
name = "rust-in-action-types-int-num_bin"
version = "0.1.0"
edition = "2021"
autobins = true

[dependencies]
num="0.4.0"

[[bin]]
doc = true
name = "rust-in-action-types-int-num-main"
path = "src/rust-in-action-types-int-num-main.rs"
