[package]
name = "rust-in-action-semantic_bin"
version = "0.1.0"
edition = "2021"
autobins = true

[[bin]]
doc = true
name = "rust-in-action-semantic-main"
path = "src/rust-in-action-semantic-main.rs"
