[package]
name = "rust-egg-lifetime-static_bin"
version = "0.1.0"
edition = "2021"
autobins = true


[[bin]]
doc = true
name = "rust-egg-lifetime-static-main"
path = "src/rust-egg-lifetime-static-main.rs"
