[package]
name = "rust-in-action-thread-time_bin"
version = "0.1.0"
edition = "2021"
autobins = true

[[bin]]
doc = true
name = "rust-in-action-thread-time-main"
path = "src/rust-in-action-thread-time-main.rs"
