[package]
edition = "2021"
name = "packtpub-smartpointer-ref-cell-linkedlist_lib"
version = "0.1.0"



[lib]
doc = true
name = "lib"
path = "src/lib.rs"
test = true

[[test]]
doc = true
name = "test"
path = "test/linkedlist.rs"
test = true