[package]
name = "rust-doc-concise-flowcontrol_bin"
version = "0.1.0"
edition = "2021"
autobins = true

[[bin]]
doc = true
name = "rust-doc-concise-flowcontrol-main"
path = "src/rust-doc-concise-flowcontrol-main.rs"
