[package]
name = "educative-types-generic_bin"
version = "0.1.0"
edition = "2021"
autobins = true


[[bin]]
doc = true
name = "educative-types-generic-main"
path = "src/educative-types-generic-main.rs"
