[package]
name = "master-rust-complex-rhs_bin"
version = "0.1.0"
edition = "2021"
autobins = true

[dependencies]
proptest="1.0.0"


[[bin]]
doc = true
name = "master-rust-complex-rhs-main"
path = "src/master-rust-complex-rhs-main.rs"
