[package]
name = "rust-in-action-duplication-rc_bin"
version = "0.1.0"
edition = "2021"



[[bin]]
doc = true
name = "rust-in-action-duplication-rc-main"
path = "src/rust-in-action-duplication-rc-main.rs"
