[package]
name = "master-rust-smartpointer-box_bin"
version = "0.1.0"
edition = "2021"



[[bin]]
doc = true
name = "master-rust-smartpointer-box-main"
path = "src/master-rust-smartpointer-box-main.rs"
