[package]
name = "eduactive-var_bin"
version = "0.1.0"
edition = "2021"
autobins = true

[dependencies]
proptest="1.0.0"

[[bin]]
doc = true
name = "eduactive-var-main"
path = "src/eduactive-var-main.rs"
