[package]
name = "rust-egg-error-handling_bin"
version = "0.1.0"
edition = "2021"


[dependencies]
rand="0.8.5"

[[bin]]
doc = true
name = "rust-egg-error-handling-main"
path = "src/rust-egg-error-handling-main.rs"
