[package]
name = "code-like-a-pro-types-string_bin"
version = "0.1.0"
edition = "2021"
autobins = true


[[bin]]
doc = true
name = "code-like-a-pro-types-string-main"
path = "src/code-like-a-pro-types-string-main.rs"
