[package]
edition = "2021"
name = "knoldus_lib"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
doc-comment = "0.3.3"
