[package]
name = "rust-in-action-trait-display_bin"
version = "0.1.0"
edition = "2021"



[[bin]]
doc = true
name = "rust-in-action-trait-display-main"
path = "src/rust-in-action-trait-display-main.rs"
