[package]
name = "rust-doc-unsafe-send-sync_bin"
version = "0.1.0"
edition = "2021"
autobins = true


[[bin]]
doc = true
name = "rust-doc-unsafe-send-sync-main"
path = "src/rust-doc-unsafe-send-sync-main.rs"
