[package]
name = "master-rust-shared-behavior-dispatchable_bin"
version = "0.1.0"
edition = "2021"



[[bin]]
doc = true
name = "master-rust-shared-behavior-dispatchable-main"
path = "src/master-rust-shared-behavior-dispatchable-main.rs"
