[package]
name = "rust-in-action-smartpointer-box_bin"
version = "0.1.0"
edition = "2021"



[[bin]]
doc = true
name = "rust-in-action-smartpointer-box-main"
path = "src/rust-in-action-smartpointer-box-main.rs"
