[package]
name = "rust-in-action-match-flowcontrol_bin"
version = "0.1.0"
edition = "2021"
autobins = true

[[bin]]
doc = true
name = "rust-in-action-match-flowcontrol-main"
path = "src/rust-in-action-match-flowcontrol-main.rs"

