[package]
name = "rust-egg-trait-associate-type-and-trait_bin"
version = "0.1.0"
edition = "2021"



[[bin]]
doc = true
name = "rust-egg-trait-associate-type-and-trait-main"
path = "src/rust-egg-trait-associate-type-and-trait-main.rs"
