[package]
name = "packtpub-loop-flowcontrol_bin"
version = "0.1.0"
edition = "2021"
autobins = true

[[bin]]
doc = true
name = "packtpub-loop-flowcontrol-main"
path = "src/packtpub-loop-flowcontrol-main.rs"
