[package]
name = "rust-doc-life-time-static_bin"
version = "0.1.0"
edition = "2021"
autobins = true

[[bin]]
doc = true
name = "rust-doc-life-time-static-main"
path = "src/rust-doc-life-time-static-main.rs"
