[package]
name = "master-rust-trait-associate-type_bin"
version = "0.1.0"
edition = "2021"



[[bin]]
doc = true
name = "master-rust-trait-associate-type-main"
path = "src/master-rust-trait-associate-type-main.rs"
