[package]
name = "rust-doc-safe-abstraction_bin"
version = "0.1.0"
edition = "2021"
autobins = true


[[bin]]
doc = true
name = "rust-doc-safe-abstraction-main"
path = "src/rust-doc-safe-abstraction-main.rs"
