[package]
name = "rust-in-action-thread-mpsc_bin"
version = "0.1.0"
edition = "2021"
autobins = true


[dependencies]
rand = "0.5.5"

[[bin]]
doc = true
name = "rust-in-action-thread-mpsc-main"
path = "src/rust-in-action-thread-mpsc-main.rs"
