[package]
name = "rust-in-action-commandline-clap_bin"
version = "0.1.0"
edition = "2021"


[dependencies]
regex = "1"
clap = "2.0.0"

[[bin]]
doc = true
name = "rust-in-action-commandline-clap-main"
path = "src/rust-in-action-commandline-clap-main.rs"
