[package]
name = "rust-doc-shared-behavior-nondispatchable_bin"
version = "0.1.0"
edition = "2021"



[[bin]]
doc = true
name = "rust-doc-shared-behavior-nondispatchable-main"
path = "src/rust-doc-shared-behavior-nondispatchable-main.rs"
