[package]
name = "educative-for-flowcontrol_bin"
version = "0.1.0"
edition = "2021"
autobins = true

[[bin]]
doc = true
name = "educative-for-flowcontrol-main"
path = "src/educative-for-flowcontrol-main.rs"
