[package]
name = "code-like-a-pro-types-int_bin"
version = "0.1.0"
edition = "2021"
autobins = true

[dependencies]
num="0.4.0"

[[bin]]
doc = true
name = "code-like-a-pro-types-int-main"
path = "src/code-like-a-pro-types-int-main.rs"
